#!/bin/bash

set -e

if git --work-tree=/deploy --git-dir=/app.git checkout -b master; then
  echo 'Initializing first setup of application!'
else
  git --work-tree=/deploy --git-dir=/app.git checkout -f master
fi

# STACK=heroku-16 /buildpack/bin/compile /deploy /tmp

# git --work-tree=/deploy --git-dir=/app.git clean -df
set -a
. /set_env_vars.sh
set +a
docker build -f /deploy/application-dockerfile -t vestibulando /deploy
tag_hash=`< /dev/urandom tr -dc a-z-0-9 | head -c8`
APPLICATION_TAG=gcr.io/$PROJECT_ID/vestibulando:$tag_hash
LATEST_TAG=gcr.io/$PROJECT_ID/vestibulando:latest
docker tag vestibulando $APPLICATION_TAG
docker tag vestibulando $LATEST_TAG
docker login -u _json_key -p "$CONTAINER_REGISTRY_SA" https://gcr.io
docker push $APPLICATION_TAG
docker push $LATEST_TAG
echo "$GKE_SA" > /keyconfig.json
/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file /keyconfig.json --project $PROJECT_ID
/google-cloud-sdk/bin/gcloud container clusters get-credentials twelve-factor --zone us-east1-c --project $PROJECT_ID
kubectl set image deployment application application=$APPLICATION_TAG
