#!/bin/bash

echo "puts ('a'..'z').to_a.shuffle[0,25].join" > file_name_generator.rb
TMP_DIRECTORY=$(ruby file_name_generator.rb)
mkdir /tmp/$TMP_DIRECTORY
/config-parser.rb $TMP_DIRECTORY
cd /tmp/$TMP_DIRECTORY

set -a
. /tmp/$TMP_DIRECTORY/set_env_vars.sh
set +a

APPLICATION_DIR=/apps/$APPLICATION_NAME

docker build -t $APPLICATION_NAME --build-arg BUILD_DIR=$APPLICATION_DIR .
HEAD=$(git --git-dir=/tmp/$TMP_DIRECTORY/.git --work-tree=/tmp/$TMP_DIRECTORY rev-parse HEAD)
APPLICATION_TAG=gcr.io/$PROJECT_ID/$APPLICATION_NAME:$HEAD
LATEST_TAG=gcr.io/$PROJECT_ID/$APPLICATION_NAME:latest

docker tag $APPLICATION_NAME $APPLICATION_TAG
docker tag $APPLICATION_NAME $LATEST_TAG
docker login -u _json_key -p "$CONTAINER_REGISTRY_SA" https://gcr.io
docker push $APPLICATION_TAG
docker push $LATEST_TAG
/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file /gke_sa.json --project $PROJECT_ID
/google-cloud-sdk/bin/gcloud container clusters get-credentials $CLUSTER --zone $ZONE
eval $BEFORE_DEPLOY_COMMAND
eval $DEPLOY_COMMAND

cd /app.git
rm -r /tmp/$TMP_DIRECTORY
